### ISSUE TITLE
大佬，乐心运动的脚本，每次修改只能打开app刷新一下才生效吗？

### ISSUE THREAD

**Issue by lxk0301** [iepngs/Script#1]
可以获取cookie。 然后task定时发送一个请求过去修改不？是cookie时效太短了？

**Comment by iepngs** [comment]
没试过，看请求数据里面有expiretimeAt字段有效期只有三天，里面有个alert的js到点会有状态栏通知出来，你点那个通知弹窗会启动app的，然后就完了

**Comment by lxk0301** [comment]
> 没试过，看请求数据里面有expiretimeAt字段有效期只有三天，里面有个alert的js到点会有状态栏通知出来，你点那个通知弹窗会启动app的，然后就完了

那行，估计是有时效的。 弹窗点击跳app这个我看到了，

**Comment by lxk0301** [comment]
@iepngs 对了。那个朋友圈去广告的。好像没有用。我圈x和loon都试过。朋友圈还是有广告的

**Comment by iepngs** [comment]
是的 没卵用，朋友圈的数据好像不是常见的数据传输
