### ISSUE TITLE
叮咚农场不能正常运行

### ISSUE THREAD

**Issue by iadao** [iepngs/Script#11]
qx，运行脚本没有任何信息显示，之前是正常的

**Comment by zy-lee** [comment]
#10 qx我在这个pr里小改了下，能跑下去了，暂时可以替换下

**Comment by iadao** [comment]
> #10 qx我在这个pr里小改了下，能跑下去了，暂时可以替换下

感谢，目前最新版本已经可以正常运行了~

**Comment by iepngs** [comment]
你们最近能正常跑吗

**Comment by zy-lee** [comment]
更新了下，又老问题了

**Comment by zy-lee** [comment]
更新也能正常了。刚巧今天完成进度，被我当成老问题了

**Comment by iepngs** [comment]
好的 我是说我用qx跑了下正常的

**Comment by iadao** [comment]
> 好的 我是说我用qx跑了下正常的

叮咚农场貌似又不能正常运行了，还是运行后什么内容都不显示，一直卡在运行界面

**Comment by iepngs** [comment]
它那个程序的接口升级了，现在同步了

**Comment by iadao** [comment]
> 它那个程序的接口升级了，现在同步了

感谢大佬，正常运行了

**Comment by iadao** [comment]
大佬，叮咚农场不能正常运行了

**Comment by 1217079729** [comment]
> 大佬，叮咚农场不能正常运行了

我的也不行了，期待大佬更新

**Comment by iepngs** [comment]
好了

**Comment by iepngs** [comment]
好了
