### ISSUE TITLE
叮咚农场有报错，写入CK正常的

### ISSUE THREAD

**Issue by Vincentzhengwei** [iepngs/Script#12]
1、叮咚买菜ck和签到是正常
2、叮咚农场的ck也提示写入成功，但是运营有以下两个不知道什么错误，会做部分任务，但是不会喂鱼

麻烦大佬帮忙看下

![image](https://user-images.githubusercontent.com/32627913/118916879-5b063880-b962-11eb-82e8-482bf7d58466.png)
![image](https://user-images.githubusercontent.com/32627913/118916871-5772b180-b962-11eb-9d19-add232294978.png)

**Comment by iepngs** [comment]
再跑一下看
你没有养龙虾吗
<img src="https://user-images.githubusercontent.com/10695382/118940572-70d82580-b983-11eb-804a-3d4f77f0d239.png" width="260px" />

**Comment by Vincentzhengwei** [comment]
> 再跑一下看
> 你没有养龙虾吗
> <img alt="" width="260px" src="https://user-images.githubusercontent.com/10695382/118940572-70d82580-b983-11eb-804a-3d4f77f0d239.png">

没有龙虾呀，龙虾怎么养的？没看到可以养的地方

**Comment by Vincentzhengwei** [comment]
> 再跑一下看
> 你没有养龙虾吗
> <img alt="" width="260px" src="https://user-images.githubusercontent.com/10695382/118940572-70d82580-b983-11eb-804a-3d4f77f0d239.png">

我朋友龙虾已经养完了只剩鱼，也是跟我一样报错

**Comment by iepngs** [comment]
更新下脚本跑一下看 还是不行么?

**Comment by Vincentzhengwei** [comment]
> 更新下脚本跑一下看 还是不行么?

开头提示：
{
    FINISHED = "\U5b8c\U6210\Uff0c\U5df2\U9886\U53d6\U5956\U52b1";
    "TO_ACHIEVE" = "\U672a\U5b8c\U6210";
    "TO_REWARD" = "\U5df2\U5b8c\U6210\Uff0c\U672a\U9886\U53d6\U5956\U52b1";
    "WAITING_REWARD" = "\U7b49\U5f85\U5b8c\U6210";
    "WAITING_WINDOW" = "\U672a\U5230\U9886\U53d6\U65f6\U95f4";
}



结尾提示：
***********叮咚农场***********
正在获取鱼池信息…

***********叮咚农场***********

***********叮咚农场***********
饲料不够，明天再喂吧。

***********叮咚农场***********
第1次喂食

***********叮咚农场***********
当前饲料剩余:5g,再喂养12次，就长成成鱼啦
null

***********叮咚农场***********
{
    code = 800;
    "exec_time" = "<null>";
    msg = "\U51fa\U4e86\U70b9\U95ee\U9898\U54e6\Uff0c\U8bf7\U7a0d\U540e\U518d\U8bd5\U5427";
    success = 0;
    timestamp = "2021-05-20 16:27:36";
}

![image](https://user-images.githubusercontent.com/32627913/118946065-a03d6100-b988-11eb-8449-fa509316ea49.png)

**Comment by iepngs** [comment]
铁子  你这个没有饲料了看起来

**Comment by Vincentzhengwei** [comment]
> 铁子 你这个没有饲料了看起来

现在确实是没有饲料，我晚点有再试试。

但是没有饲料，会导致loon直接横幅提示“叮咚农场，props/feed，出了点问题哦”。

开头的这部分提示，无论是有饲料还是没有都会提示
{
FINISHED = "\U5b8c\U6210\Uff0c\U5df2\U9886\U53d6\U5956\U52b1";
"TO_ACHIEVE" = "\U672a\U5b8c\U6210";
"TO_REWARD" = "\U5df2\U5b8c\U6210\Uff0c\U672a\U9886\U53d6\U5956\U52b1";
"WAITING_REWARD" = "\U7b49\U5f85\U5b8c\U6210";
"WAITING_WINDOW" = "\U672a\U5230\U9886\U53d6\U65f6\U95f4";
}

**Comment by Vincentzhengwei** [comment]
@iepngs 我找我好友拿了他的号，他的【有饲料】【龙虾养完了】，同样会提示报错。劳烦看看
![image](https://user-images.githubusercontent.com/32627913/118960229-a6860a00-b995-11eb-8928-91a4a1991731.png)
![image](https://user-images.githubusercontent.com/32627913/118960253-aede4500-b995-11eb-9d90-65e82e72acd2.png)
![image](https://user-images.githubusercontent.com/32627913/118960273-b271cc00-b995-11eb-8da9-095750c305f3.png)

**Comment by iepngs** [comment]
有空更新了再试一下看 我这数据不一样 也是盲猜着改。。

**Comment by Vincentzhengwei** [comment]
> 有空更新了再试一下看 我这数据不一样 也是盲猜着改。。

更新之后，第一次运行正常了。第二次运行，对于饲料不足的判断可能还有小小问题

![image](https://user-images.githubusercontent.com/32627913/119073473-00331680-ba20-11eb-8dfb-db9385bd7757.png)

{
code = 800;
"exec_time" = "";
msg = "\U51fa\U4e86\U70b9\U95ee\U9898\U54e6\Uff0c\U8bf7\U7a0d\U540e\U518d\U8bd5\U5427";
success = 0;
timestamp = "2021-05-20 16:27:36";
}

**Comment by iepngs** [comment]
处理掉了

**Comment by Vincentzhengwei** [comment]
> 处理掉了

OK了，感谢大大
