### ISSUE TITLE
叮咚买菜报错了

### ISSUE THREAD

**Issue by songyangzz** [iepngs/Script#6]
2020/11/14 22:17:39:301  <console>    [JS Console]: ❌ 叮咚买菜 signapp - response: {"headers":{"Transfer-Encoding":"chunked","Content-Type":"text/html; charset=utf-8","Connection":"close","Server":"nginx","Date":"Sat, 14 Nov 2020 14:17:39 GMT"},"statusCode":400,"body":"<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"}

**Comment by songyangzz** [comment]
目测是浏览商品任务没了.

**Comment by songyangzz** [comment]
异常里面转string报错了.返回的不是JSON.麻烦大佬了.

**Comment by iepngs** [comment]
我看日志这里没有你这种记录 明天我确认一下

**Comment by songyangzz** [comment]
> 我看日志这里没有你这种记录 明天我确认一下
> 
> > 在 2020年11月14日，22:31，songyangzz <notifications@github.com> 写道：
> > 
> > ﻿
> > 异常里面转string报错了.返回的不是JSON.麻烦大佬了.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

找错人了...农场没问题.是买菜签到报错了.
